# Generated by Django 4.1 on 2023-01-02 10:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('desc', models.TextField(max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('icon_url', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Company',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Saved_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_open', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved_Company',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('base', models.PositiveIntegerField(default=0)),
                ('bonus', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.company')),
            ],
            options={
                'verbose_name_plural': 'Salary',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='New_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('job_id', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.company')),
            ],
            options={
                'verbose_name_plural': 'New_Jobs',
                'ordering': ('id',),
            },
        ),
    ]
